### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by femke77** [blairjordan/codachi#15]
Codachi: Show Panel gives the not found error
Tried reinstalling, reloading vs code. Nothing works.

**Comment by blairjordan** [comment]
Thanks for the issue.

Two things: 
- Do you have any [VIM plugins installed](https://github.com/blairjordan/codachi/issues/3)?

- Can you possibly do me a favour and tell me if there's any errors in the console? (View > Debug Console)

![screenshot-2023-08-28_10-07_1](https://github.com/blairjordan/codachi/assets/998930/40fbeabe-70e7-4303-b946-e59c9bfd66e8)

**Comment by blairjordan** [comment]
Can't replicate without further debugging info, so I'll close this for now.
For now, assuming it's related to issue https://github.com/blairjordan/codachi/issues/3

**Comment by femke77** [comment]
No VIM plug-ins at all
Nothing in the debug console.
